# 使用一个基础镜像，这里以 Node.js 官方镜像为例
FROM node:latest

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 文件到容器中
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制项目文件到容器中
COPY . .

# 暴露容器的端口，如果你的应用使用了特定的端口，请修改为相应的端口号
EXPOSE 9999

# 运行项目
CMD ["npm", "run", "start:dev"]